name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Install package
        run: pip install -e .
      - name: Collect tests
        run: pytest --collect-only -q
      - name: Run tests
        run: pytest --tb=short
